### ISSUE TITLE
port 181 probably shouldn't be a default.

### ISSUE THREAD

**Issue by gregf** [v4rakh/docker-filebin#4]
Hi,

Using port 181 requires the container to run as root, and you shouldn't run docker containers as the root user. What about changing the default to 8080 or anything in the higher ranges?

Thank for the well crafted compose file and image. I started to use it earlier today and it's working well so far.

**Comment by v4rakh** [comment]
Hi,

thanks for your feedback. I'll later look into this and change to be able to run on `8080` by default.
